### PR TITLE
Added Vue Router

### PR DESCRIPTION
**Pull request by JeremyBYU**
Added Vue Router as well as removed memory leak of socket io events.
The actions `addMessage` and `removeMessage` create event functions that
never get removed.  In other words if a route changes or a hot reload
occurs (component reloads) then new `addMessage` listeners and
`removeMessage` listeners will be created; and the previous ones are not
removed. This leads to a memory leak as well as duplicate messages being
stored in the state.  This causes issues with rendering as well for the
v-for list.

P.S. - I also introduced a bug in my last pull request that this pull request resolves.  
Bug in File `Messages.vue`
From `services.messageService.remove(message)`
To `services.messageService.remove(message._id)`

### CODE REVIEW

**Comment by niallobrien** [comment]
Thank you for the PR.

Is there any particular reason why this example needs Vue Router?
I created this example purely to demonstrate Vuex and am slightly concerned of the amount of code changes in this PR which will deviate from what's demonstrated in the video.
I do think that removing the event listeners is a good suggestion though.

**Comment by JeremyBYU** [comment]
No your right, the vue router does deviate too much from the video. Is there away where you can pick and choose the event listener and removeMesaage fix? If not I'll submit a different pr. Thanks!

Sent from my Windows 10 phone

**Comment by kristianmandrup** [comment]
Hey guys, could one of you please upgrade the project to Vue 2. I was trying, but getting errors:

```
[Vue warn]: Avoid adding reactive properties to a Vue instance or its root $data at runtime - declare it upfront in the data option. 
```

Updated `vue` to `^2.0.3` and `vue-loader` to `^9.0.0` so far

Not sure how to correct the error. Please advice ;)

**Comment by kristianmandrup** [comment]
Made various other module upgrades and a few code changes... Continued from @JeremyBYU fork

[vue2 branch](https://github.com/kristianmandrup/feathers-chat-example/tree/vue2)

Would be awesome if you could help out :)

**Comment by niallobrien** [comment]
Hey guys, I'm on mobile at the minute - if someone wants to upgrade this example to v2 and submit a PR, please do.

**Pull request closed without merging**
